### ISSUE TITLE
我这边用了，但是没有任何内容显示呢？怎么排查呢？

### ISSUE THREAD

**Issue by agentwx** [beiliao-web-frontend/wepy-html#6]
已经按照readme里面进行了依赖项的安装，wepy.config里面也增加了配置

  import WepyHTML from 'wepy-html';

![image](https://user-images.githubusercontent.com/3361014/54516983-739df100-499b-11e9-9683-9be8bc18fdb2.png)

但是结果显示出来的是空白，也没有报错

**Comment by agentwx** [comment]
<template>
    <view class="detail-body">
      <view class="detail-body__header">
        <view class="detail-body__all-title">
          <text class="detail-body__title">{{ detail.title }}</text>
        </view>
      </view>      
      <view class="split-line"></view>
      <view class="f-col">
        <view class="detail-update__version">
          <text class="detail-auth">作者: {{ detail.usrname }}</text>
          <text class="detail-date">{{ detail.createtime }}</text>
        </view>
      </view>

      <view class="split-line"></view>
      <view class="detail-describe f-col">
        <template lang="wxml">
          <wepy-html />
        </template>
        
      </view>
    </view>
</template>

  import wepy from 'wepy';
  import fetch from "@/service/fetch";  
  import WepyHTML from 'wepy-html';


    data = {
    	id: null,
      isUpdateOpen: false,
      isDescribeOpen: false,      
      detail:""
    }


    async onLoad(option) {
      console.log(option.id);
      let m_detail = await fetch.get(
        "/post/v1/postservice?query=info&id="+option.id,
        {},
        false,
        false
      );
      this.detail = m_detail
      console.log(this.detail);
		// 调用组件接口，传入HTML内容和相关参数
     this.$invoke('wepy-html', 'updateContent', this.detail.body, {});      
      this.$apply()
    }

this.body.detail里的内容是：
"<p>在门户网站和传统新闻客户端上，哪些文章能上首页是由编辑们决定的，编辑们会在阅读完文章后，会决定是否将其推上版面。因为每个用户看到的页面都是相同的，编辑们的工作量虽然大，但还能够应付。而在今日头条客户端上，每位用户的信息流都是完全不同的，如果5亿用户的信息流都交由编辑来推荐，则是一件不可能完成的任务。</p><p>但是机器可以做到，因为其「阅读」文章的方式，在速度上要远远胜过人类。系统会对文章进行特征识别，从而判断文章讲的是什么类型和领域的内容。特征识别的维度有很多，在这里我们重点解释「关键词」。</p><p>系统会根据文章中出现的频率，提取出一些词语作为关键词，关键词的判定原则有二：</p><ul><li><strong>词频高：</strong>如一篇体育类文章内容关于某场足球比赛，那么文章可能会出现的高频词就包括球员名字、足球术语或技巧等，如「C 罗」、「射门」、「突破」。</li><li><strong>同类文章中出现次数少：</strong>作者撰文时常用到的虚词、转折词等出现频率也很高，但它们不会作为关键词被提取出来，因为这些词在文章中是普遍存在的。</li></ul><p>系统判定出一篇文章的关键词后，会将这些关键词与文章分类模型进行比对，命中哪些分类词库关键词的比例大，文章即被打上该分类的标签。</p><p>如，一篇文章排名靠前的关键词为「C 罗」、「射门」、「西甲」、「马德里」，那么该篇文章可能会被打上「足球」、「国际足球」、「西班牙」等标签。机器便是这样，完成对文章的初步认知。</p><p>因为这种关键词识别机制的存在，作者应尽量避免在文中过度使用非常规词语，如活久见、腿玩年、城会玩等，给自己的文章增加理解障碍。行文用词规范，机器可能更懂你的文章。</p><p>除文章正文关键词识别外，机器还会对标题进行关键词的识别和分类比对。因此，在标题中露出具代表性的实体词，可帮助机器理解你的文章。</p><p>例如，同样一篇足球类文章，标题「大胡子梅西，大胡子阿奎罗，大胡子伊瓜因，阿根廷美洲杯冠军稳了！」，就比标题「三人蓄须明志，誓要实现多年远大理想」含义更明确，更利于系统识别，获得更多的推荐量。</p>"

（用小程序自带的rich-text可以显示出来，只是感觉不好控制,所以还是尝试下你的作品)
另：
  "dependencies": {
    "less": "^3.9.0",
    "redux": "^3.7.2",
    "redux-actions": "^2.2.1",
    "redux-promise": "^0.5.3",
    "wepy": "^1.7.2",
    "wepy-async-function": "^1.4.4",
    "wepy-com-toast": "^1.0.2",
    "wepy-compiler-sass": "^1.3.12",
    "wepy-html": "^0.1.4",
    "wepy-redux": "^1.5.9"
  }

**Comment by heeroluo** [comment]
> <template lang="wxml">
>           <wepy-html />
>         </template>

请把 wepy-html 外层的 template 标签去掉

**Comment by agentwx** [comment]
可以了，谢谢，我以为<template lang="wxml">这个标签里面的wxml是必须的
